apiVersion: redhatcop.redhat.io/v1alpha1
kind: GlobalRouteDiscovery
metadata:
  name: external-dns-globalroutediscovery
spec:
  clusters:
  - clusterName: cluster1
    clusterCredentialRef:
      name: ${cluster1_secret_name}
      namespace: ${cluster1_namespace}
  - clusterName: cluster2
    clusterCredentialRef:
      name: ${cluster2_secret_name}
      namespace: ${cluster1_namespace}
  - clusterName: cluster3
    clusterCredentialRef:
      name: ${cluster3_secret_name}
      namespace: ${cluster1_namespace}
  routeSelector:
    matchLabels:
      route-type: global
  defaultLoadBalancingPolicy: Multivalue
  defaultTTL: 30 
  globalZoneRef:
    name: external-dns-zone