apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: route53-global-zone-credentials
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries: 
    - action:
      - "route53:GetHostedZone"
      - "route53:CreateTrafficPolicy"
      - "route53:DeleteTrafficPolicy"
      - "route53:GetTrafficPolicy"
      - "route53:ListTrafficPolicies"
      - "route53:CreateTrafficPolicyInstance"
      - "route53:DeleteTrafficPolicyInstance"
      - "route53:GetTrafficPolicyInstance"
      - "route53:ListTrafficPolicyInstancesByHostedZone"     
      - "route53:ListTrafficPolicyInstancesByPolicy"
      - "route53:ListHealthChecks"
      - "route53:GetHealthCheck"
      - "route53:UpdateHealthCheck"
      - "route53:DeleteHealthCheck"
      - "route53:CreateHealthCheck"
      - "tag:TagResources"
      effect: Allow
      resource: '*'
  secretRef:
    name: route53-global-zone-credentials
    namespace: ${namespace}