apiVersion: redhatcop.redhat.io/v1alpha1
kind: GlobalRouteDiscovery
metadata:
  name: route53-globalroutediscovery
spec:
  clusters:
  - clusterName: cluster1
    clusterCredentialRef:
      name: ${cluster1_secret_name}
      namespace: cluster1
  - clusterName: cluster2
    clusterCredentialRef:
      name: ${cluster2_secret_name}
      namespace: cluster2
  - clusterName: cluster3
    clusterCredentialRef:
      name: ${cluster3_secret_name}
      namespace: cluster3
  routeSelector:
    matchLabels:
      route-type: global
  defaultLoadBalancingPolicy: Multivalue
  defaultTTL: 30 
  globalZoneRef:
    name: route53-global-dns-zone